// posts
export const FETCH_POSTS__REQUEST = "FETCH_POSTS__REQUEST";
export const FETCH_POSTS_SUCCESS_REQUEST = "FETCH_POSTS_SUCCESS_REQUEST";
export const FETCH_POSTS_FAILURE_REQUEST = "FETCH_POSTS_FAILURE_REQUEST";

// comments
export const FETCH_COMMENTS__REQUEST = "FETCH_COMMENTS__REQUEST";
export const FETCH_COMMENTS_SUCCESS_REQUEST = "FETCH_COMMENTS_SUCCESS_REQUEST";
export const FETCH_COMMENTS_FAILURE_REQUEST = "FETCH_COMMENTS_FAILURE_REQUEST";

// users

export const FETCH_USERS__REQUEST = "FETCH_USERS__REQUEST";
export const FETCH_USERS_SUCCESS_REQUEST = "FETCH_USERS_SUCCESS_REQUEST";
export const FETCH_USERS_FAILURE_REQUEST = "FETCH_USERS_FAILURE_REQUEST";

// SIGNUP

export const FETCH_SIGNUP__REQUEST = "FETCH_USERS__REQUEST";
export const FETCH_SIGNUP_SUCCESS_REQUEST = "FETCH_USERS_SUCCESS_REQUEST";
export const FETCH_SIGNUP_FAILURE_REQUEST = "FETCH_USERS_FAILURE_REQUEST";

// USERPHOTO
export const FETCH_USERPHOTO__REQUEST = "FETCH_USERS__REQUEST";
export const FETCH_USERPHOTO_SUCCESS_REQUEST = "FETCH_USERS_SUCCESS_REQUEST";
export const FETCH_USERPHOTO_FAILURE_REQUEST = "FETCH_USERS_FAILURE_REQUEST";